import {api} from './api';
import {useEffect,useState} from 'react';
import {LayoutDashboard,CalendarDays,ListTodo,History,Plus,ArrowUpRight,Search,Download,CheckCircle2,Clock,AlertTriangle,ChevronRight,X,Leaf,FileText,Save} from 'lucide-react';
const statuses=['A iniciar','Pendente','Em curso','Finalizado'];
const date=(d:string)=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-PT'):'Sem prazo';
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Lisbon'}).format(new Date());
const plusDays=(d:string,n:number)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const urgency=(a:any)=>a.status==='Finalizado'?'done':!a.due?'none':a.due<today()?'late':a.due<=plusDays(today(),7)?'soon':'none';
const badge=(a:any)=><span className={'badge '+(a.status==='Finalizado'?'done':a.status==='Em curso'?'progress':'pending')}>{a.status}</span>;
export default function Hub(){
 const [state,setState]=useState<any>(null),[revision,setRevision]=useState(0),[view,setView]=useState('Dashboard'),[meetingId,setMeetingId]=useState('m1'),[search,setSearch]=useState(''),[area,setArea]=useState(''),[status,setStatus]=useState(''),[owner,setOwner]=useState(''),[deadline,setDeadline]=useState(''),[modal,setModal]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){try{const j:any=await api('read');setState(j.data);setRevision(j.revision);}catch(e:any){setError(e.message);}}
 useEffect(()=>{load()},[]);
 async function save(operation:string,payload:any){const {action,...cleanPayload}=payload;setBusy(true);setError('');try{const j:any=await api('mutate',{revision,operation,payload:cleanPayload});setState(j.data);setRevision(j.revision);setModal(null);setNotice('Guardado com sucesso');if(operation==='next'){setMeetingId(j.data.meetings.at(-1).id);setView('Reuniões');}return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 if(!state)return <div className="loading"><Leaf size={40}/><h1>MDP Meeting Hub</h1><p>{error||'A carregar os assuntos do Comité de Gestão…'}</p>{error&&<button onClick={load}>Tentar novamente</button>}</div>;
 const actions=state.actions,meetings=state.meetings,m=meetings.find((x:any)=>x.id===meetingId)||meetings.at(-1),areas=Array.from(new Set(actions.map((a:any)=>a.area))) as string[],owners=Array.from(new Set(actions.flatMap((a:any)=>a.owner.split('/')))).sort() as string[];
 const open=actions.filter((a:any)=>a.status!=='Finalizado'),late=open.filter((a:any)=>urgency(a)==='late'),soon=open.filter((a:any)=>urgency(a)==='soon').sort((a:any,b:any)=>a.due.localeCompare(b.due));
 const meetingActions=m.snapshots||actions.filter((a:any)=>m.actionIds.includes(a.id));
 const base=view==='Reuniões'?meetingActions:actions;
 const filtered=base.filter((a:any)=>(!area||a.area===area)&&(!status||a.status===status)&&(!owner||a.owner.split('/').includes(owner))&&(!deadline||urgency(a)===deadline)&&(!search||(a.title+' '+a.updates.at(-1).text+' '+a.owner).toLocaleLowerCase().includes(search.toLocaleLowerCase())));
 const edit=(a?:any)=>setModal({type:'action',id:a?.id,area:a?.area||areas[0],title:a?.title||'',owner:a?.owner||'',status:a?.status||'A iniciar',due:a?.due||'',text:'',meetingId:m.id,action:a});
 function download(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='MDP-backup-'+today()+'.json';link.click();URL.revokeObjectURL(url);}
 const nav=[['Dashboard',LayoutDashboard],['Reuniões',CalendarDays],['Ações',ListTodo],['Histórico',History]] as const;
 const reset=()=>{setArea('');setOwner('');setStatus('');setDeadline('');setSearch('')};
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="mark"><Leaf/></div><div>MONTE DO PASTO<small>MEETING HUB</small></div></div><div className="navlabel">COMITÉ DE GESTÃO</div><nav>{nav.map(([name,Icon])=><button key={name} className={view===name?'active':''} onClick={()=>{setView(name);reset()}}><Icon size={19}/>{name}{name==='Ações'&&<span>{open.length}</span>}</button>)}</nav><div className="sidebottom"><div className="sync"><i/> Dados guardados no Google Sheets</div><button onClick={download}><Download size={17}/> Exportar cópia de segurança</button><small>Monte do Pasto · Comité de Gestão</small></div></aside>
 <main><header className="topbar"><span>Workspace <ChevronRight size={14}/> Comité de Gestão</span><div><span className="date">{date(today())}</span><div className="avatar">MDP</div></div></header><div className="content"><div className="pagehead"><div><p className="eyebrow">MONTE DO PASTO / GESTÃO</p><h1>{view==='Dashboard'?'Uma visão clara. Ações em dia.':view==='Reuniões'?'Reunião do Comité de Gestão':view==='Ações'?'Todos os assuntos, num só lugar.':'Memória das decisões.'}</h1><p>{view==='Dashboard'?'O essencial para preparar a reunião e acompanhar o que ficou decidido.':view==='Histórico'?'Consulte as reuniões e os registos preservados ao longo do tempo.':'Responsáveis, prazos e pontos de situação sempre à mão.'}</p></div><button className="primary" onClick={()=>{setMeetingId(meetings.at(-1).id);setModal({type:'action',area:areas[0],title:'',owner:'',status:'A iniciar',due:'',text:'',meetingId:meetings.at(-1).id})}} disabled={meetings.at(-1).status!=='Aberta'}><Plus size={18}/> Novo assunto</button></div>
 {error&&<div className="alert error" role="alert">{error}<button onClick={()=>{setError('');load()}}>Atualizar dados</button></div>}{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Fechar aviso"><X size={16}/></button></div>}
 {view==='Dashboard'&&<><div className="metrics">{[[open.length,'Ações abertas','Por acompanhar',ListTodo,''],[late.length,'Em atraso','Precisam de atenção',AlertTriangle,'red'],[soon.length,'Próximos 7 dias','Prazos a aproximar-se',Clock,'gold'],[actions.filter((a:any)=>a.status==='Finalizado').length,'Concluídas','Decisões concretizadas',CheckCircle2,'green']].map(([n,label,sub,Icon,color]:any)=><button className={'metric '+color} key={label} onClick={()=>{setView('Ações');reset();if(color==='red')setDeadline('late');else if(color==='gold')setDeadline('soon');else if(color==='green')setStatus('Finalizado');else setStatus('')}}><div>{label}<Icon size={20}/></div><strong>{n}</strong><small>{sub}</small></button>)}</div><div className="dashboardgrid"><section className="meetinghero"><div><span className="pill">{meetings.at(-1).status==='Aberta'?'REUNIÃO ABERTA':'ÚLTIMA REUNIÃO'}</span><h2>Comité de Gestão</h2><p>{date(meetings.at(-1).date)} <span>·</span> {meetings.at(-1).location}</p><div className="people">{meetings.at(-1).participants.split('/').filter(Boolean).slice(0,6).map((p:string,i:number)=><span key={i}>{p}</span>)}<small>{meetings.at(-1).participants.split('/').filter(Boolean).length} presenças registadas</small></div><button onClick={()=>{setMeetingId(meetings.at(-1).id);setView('Reuniões');reset()}}>Abrir reunião <ArrowUpRight size={17}/></button></div><div className="heroleaf"><Leaf size={110}/></div></section><section className="panel distribution"><div className="sectiontitle"><h2>Ações por área</h2><small>{open.length} abertas</small></div>{areas.map(a=><button key={a} onClick={()=>{setView('Ações');reset();setArea(a)}}><span>{a}</span><div className="bar"><i style={{width:Math.max(3,open.filter((x:any)=>x.area===a).length/open.length*100)+'%'}}/></div><b>{open.filter((x:any)=>x.area===a).length}</b></button>)}</section></div><div className="sectiontitle"><div><h2>O que precisa de atenção</h2><p>Prazos próximos e assuntos em atraso.</p></div><button className="textbutton" onClick={()=>{setView('Ações');reset()}}>Ver todas as ações <ArrowUpRight size={16}/></button></div><div className="panel">{[...late.sort((a:any,b:any)=>a.due.localeCompare(b.due)),...soon].slice(0,6).map((a:any)=><button className="attention" key={a.id} onClick={()=>{setMeetingId(meetings.at(-1).id);setModal({type:'detail',action:a})}}><span className={'attentionicon '+urgency(a)}><Clock size={18}/></span><div><strong>{a.title}</strong><small>{a.area} · {a.owner}</small></div>{badge(a)}<span className={'due '+urgency(a)}>{date(a.due)}</span><ChevronRight size={17}/></button>)}{!late.length&&!soon.length&&<p className="empty">Sem prazos próximos ou ultrapassados.</p>}</div><div className="source">Importação inicial: 40 assuntos · 7 áreas · Ata de 07/10/2026. Os textos originais foram preservados.</div></>}
 {view==='Histórico'&&<div className="meetinglist">{[...meetings].reverse().map((x:any,i:number)=><button className="panel historycard" key={x.id} onClick={()=>{setMeetingId(x.id);setView('Reuniões');reset()}}><div className="calendaricon"><CalendarDays size={24}/></div><div><h2>Comité de Gestão · {date(x.date)}</h2><p>{x.location} · {x.actionIds.length} assuntos</p></div><span className={'badge '+(x.status==='Encerrada'?'done':'progress')}>{x.status}</span><ChevronRight size={20}/></button>)}<p className="source">As reuniões encerradas conservam uma cópia dos assuntos e updates tal como estavam no momento do encerramento.</p></div>}
 {view==='Reuniões'&&<><section className="panel meetingmeta"><div><label>Reunião</label><select value={m.id} onChange={e=>{setMeetingId(e.target.value);reset()}}>{[...meetings].reverse().map((x:any)=><option value={x.id} key={x.id}>{date(x.date)} · {x.status}</option>)}</select><p>{m.location}</p><small>Participantes: {m.participants}</small></div><div className="meetingbuttons"><button onClick={()=>setModal({type:'minutes'})}><FileText size={17}/> Gerar ata</button>{m.status==='Aberta'?<><button onClick={()=>setModal({type:'meeting',location:m.location,participants:m.participants,meetingId:m.id})}>Editar reunião</button><button className="primary" onClick={()=>setModal({type:'close',meetingId:m.id})}>Encerrar reunião</button></>:<button className="primary" disabled={meetings.some((x:any)=>x.status==='Aberta')} onClick={()=>setModal({type:'next',date:plusDays(meetings.at(-1).date,7),location:m.location,participants:m.participants})}>Preparar próxima reunião <ArrowUpRight size={16}/></button>}</div></section>{m.status==='Encerrada'&&<p className="source">Reunião encerrada. Este registo permanece preservado; novos updates são feitos na reunião seguinte.</p>}</>}
 {(view==='Ações'||view==='Reuniões')&&<><div className="filters"><div className="search"><Search size={18}/><input placeholder="Pesquisar assunto ou ponto de situação…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Área" value={area} onChange={e=>setArea(e.target.value)}><option value="">Todas as áreas</option>{areas.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Responsável" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Responsável</option>{owners.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Estado" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os estados</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Prazo" value={deadline} onChange={e=>setDeadline(e.target.value)}><option value="">Todos os prazos</option><option value="late">Em atraso</option><option value="soon">Próximos 7 dias</option><option value="none">Outros / sem prazo</option></select><button onClick={reset}>Limpar</button></div><div className="sectiontitle"><h2>{filtered.length} assuntos</h2><small>Clique num assunto para consultar o histórico</small></div><div className="panel tablewrap"><table><thead><tr><th>Assunto / Área</th><th>Responsável</th><th>Estado</th><th>Prazo</th><th/></tr></thead><tbody>{filtered.map((a:any)=><tr key={a.id}><td><button className="rowtitle" onClick={()=>setModal({type:'detail',action:a})}><strong>{a.title}</strong><small>{a.area}</small></button></td><td><span className="owner">{a.owner}</span></td><td>{badge(a)}</td><td className={'due '+urgency(a)}>{date(a.due)}{urgency(a)==='late'&&<small>Em atraso</small>}</td><td><button aria-label={'Abrir '+a.title} onClick={()=>setModal({type:'detail',action:a})}><ChevronRight size={18}/></button></td></tr>)}</tbody></table>{!filtered.length&&<p className="empty">Nenhum assunto corresponde aos filtros.</p>}</div></>}
 </div><footer>MDP Meeting Hub <span>Continuidade em cada reunião.</span></footer></main>
 {modal&&<div className="overlay" onClick={()=>!busy&&setModal(null)}><section className={'dialog '+(modal.type==='minutes'?'wide':'')} role="dialog" aria-modal="true" aria-label="Detalhes" onClick={e=>e.stopPropagation()}><button className="close" disabled={busy} aria-label="Fechar" onClick={()=>setModal(null)}><X/></button>
 {modal.type==='detail'&&<><p className="eyebrow">{modal.action.area}</p><h2>{modal.action.title}</h2><div className="detailmeta">{badge(modal.action)}<span>{modal.action.owner}</span><span className={'due '+urgency(modal.action)}>{date(modal.action.due)}</span></div><h3>Histórico de pontos de situação</h3><div className="timeline">{[...modal.action.updates].reverse().map((u:any,i:number)=><article key={i}><div><b>{date(meetings.find((x:any)=>x.id===u.meetingId)?.date||u.at.slice(0,10))}</b><small>{u.kind} · {u.status} · {u.owner}</small></div><p>{u.text}</p><small>Prazo registado: {date(u.due)}</small></article>)}</div>{modal.action.source&&<p className="source">Origem: {state.source} · {modal.action.source.sheet}, linha {modal.action.source.row}</p>}<button className="primary" disabled={m.status!=='Aberta'||!m.actionIds.includes(modal.action.id)} onClick={()=>edit(modal.action)}><Plus size={17}/> Acrescentar ponto de situação</button></>}
 {modal.type==='action'&&<><p className="eyebrow">REUNIÃO · {date(meetings.find((x:any)=>x.id===modal.meetingId)?.date)}</p><h2>{modal.id?'Atualizar assunto':'Novo assunto'}</h2><p className="hint">Cada atualização acrescenta um registo ao histórico.</p><form onSubmit={e=>{e.preventDefault();save('action',modal)}}><label>Área<input required list="areas" value={modal.area} onChange={e=>setModal({...modal,area:e.target.value})}/><datalist id="areas">{areas.map(x=><option key={x}>{x}</option>)}</datalist></label><label>Assunto<input required value={modal.title} onChange={e=>setModal({...modal,title:e.target.value})}/></label><div className="formrow"><label>Responsável<input required placeholder="Ex.: PH/JSP" value={modal.owner} onChange={e=>setModal({...modal,owner:e.target.value})}/></label><label>Prazo<input type="date" value={modal.due} onChange={e=>setModal({...modal,due:e.target.value})}/></label></div><label>Estado<select value={modal.status} onChange={e=>setModal({...modal,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>Ponto de situação / decisão<textarea required rows={6} value={modal.text} onChange={e=>setModal({...modal,text:e.target.value})} placeholder="O que foi discutido ou decidido nesta reunião?"/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}><Save size={17}/>{busy?'A guardar…':'Guardar atualização'}</button></form></>}
 {modal.type==='meeting'&&<><h2>Dados da reunião</h2><form onSubmit={e=>{e.preventDefault();save('meeting',modal)}}><label>Local<input required value={modal.location} onChange={e=>setModal({...modal,location:e.target.value})}/></label><label>Participantes<textarea value={modal.participants} onChange={e=>setModal({...modal,participants:e.target.value})}/></label><button className="primary" disabled={busy}>Guardar</button></form></>}
 {modal.type==='close'&&<><h2>Encerrar a reunião?</h2><p>A ata e os {m.actionIds.length} assuntos ficarão preservados tal como estão agora. Depois poderá preparar a próxima reunião com os assuntos não concluídos.</p><button className="primary" disabled={busy} onClick={()=>save('close',modal)}>Confirmar encerramento</button></>}
 {modal.type==='next'&&<><h2>Preparar a próxima reunião</h2><p>Transitam automaticamente {open.length} assuntos não concluídos, com todo o histórico.</p><form onSubmit={e=>{e.preventDefault();save('next',modal)}}><label>Data<input type="date" required min={plusDays(meetings.at(-1).date,1)} value={modal.date} onChange={e=>setModal({...modal,date:e.target.value})}/></label><label>Local<input required value={modal.location} onChange={e=>setModal({...modal,location:e.target.value})}/></label><label>Participantes<textarea value={modal.participants} onChange={e=>setModal({...modal,participants:e.target.value})}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>Criar reunião</button></form></>}
 {modal.type==='minutes'&&<><div className="printcontrols"><button className="primary" onClick={()=>window.print()}><Download size={17}/> Imprimir / Guardar PDF</button><p>Escolha “Guardar como PDF” na janela de impressão.</p></div><div className="minutes"><div className="minutesbrand"><Leaf/> MONTE DO PASTO</div><p className="eyebrow">COMITÉ DE GESTÃO</p><h1>Ata de reunião</h1><p>N.º {meetings.findIndex((x:any)=>x.id===m.id)+1} · {date(m.date)} · {m.status==='Aberta'?'Minuta — reunião aberta':'Ata encerrada'}</p><div className="minutesmeta"><b>Local:</b> {m.location}<br/><b>Participantes:</b> {m.participants}</div>{areas.filter(a=>meetingActions.some((x:any)=>x.area===a)).map(a=><section key={a}><h2>{a}</h2>{meetingActions.filter((x:any)=>x.area===a).map((x:any)=><article key={x.id}><h3>{x.title}</h3><p className="minutessub">Responsável: {x.owner} · Estado: {x.status} · Prazo: {date(x.due)}</p>{x.updates.filter((u:any)=>u.meetingId===m.id).length?x.updates.filter((u:any)=>u.meetingId===m.id).map((u:any,i:number)=><p className="prewrap" key={i}>{u.text}</p>):<><small>Transitado da reunião anterior · último ponto de situação:</small><p className="prewrap">{x.updates.at(-1).text}</p></>}</article>)}</section>)}<div className="signature">Elaborado por: ____________________ <span>Aprovado por: ____________________</span></div><p className="source">MDP Meeting Hub · Monte do Pasto · Comité de Gestão</p></div></>}
 </section></div>}
 </div>;
}
